// Inlines every Vite single-file widget build (.vite-ui/<widget>/index.html) into
// one TS module (src/ui/widgets.generated.ts) so the server can return them as UI
// resources without reading from disk at runtime. This keeps the widgets working
// identically whether the server runs from the npm package (stdio) or a bundled
// host (e.g. Smithery streamable-HTTP).
//
// Run as part of `npm run build:ui` (after `vite build`).
import { readdir, readFile, writeFile } from "node:fs/promises";
import { fileURLToPath } from "node:url";

const outDir = new URL("../.vite-ui/", import.meta.url);
const dirents = await readdir(outDir, { withFileTypes: true });

const widgets = {};
for (const d of dirents) {
  if (!d.isDirectory()) continue;
  widgets[d.name] = await readFile(new URL(`${d.name}/index.html`, outDir), "utf-8");
}

const banner =
  "// AUTO-GENERATED by scripts/embed-ui.mjs from src/ui/*/ — do not edit by hand.\n" +
  "// Run `npm run build:ui` to regenerate.\n";
const body = Object.entries(widgets)
  .map(([k, v]) => `  ${JSON.stringify(k)}: ${JSON.stringify(v)},`)
  .join("\n");

await writeFile(
  fileURLToPath(new URL("../src/ui/widgets.generated.ts", import.meta.url)),
  `${banner}export const WIDGET_HTML: Record<string, string> = {\n${body}\n};\n`,
  "utf-8",
);

console.error(
  `[embed-ui] wrote ${Object.keys(widgets).length} widget(s): ${Object.keys(widgets).join(", ") || "(none)"}`,
);
