// Inlines the Vite single-file build (.vite-ui/index.html) into a TS module so
// the server can return it as a UI resource without reading from disk at runtime.
// This keeps the composer working identically whether the server runs from the
// npm package (stdio) or a bundled host (e.g. Smithery streamable-HTTP).
//
// Run as part of `npm run build:ui` (after `vite build`).
import { readFile, writeFile } from "node:fs/promises";
import { fileURLToPath } from "node:url";

const root = new URL("../", import.meta.url);
const htmlPath = new URL(".vite-ui/index.html", root);
const outPath = new URL("src/ui/composer.generated.ts", root);

const html = await readFile(htmlPath, "utf-8");

const banner =
  "// AUTO-GENERATED by scripts/embed-ui.mjs from src/ui/composer/ — do not edit by hand.\n" +
  "// Run `npm run build:ui` to regenerate.\n";

await writeFile(
  fileURLToPath(outPath),
  `${banner}export const COMPOSER_HTML = ${JSON.stringify(html)};\n`,
  "utf-8",
);

console.error(
  `[embed-ui] wrote src/ui/composer.generated.ts (${html.length} bytes of HTML)`,
);
